export const CHANGE_CURRENT_SONG = 'player/CHANGE_CURRENT_SONG'
export const CHANGE_PLAY_LIST = 'player/CHANGE_PLAY_LIST'
export const CHANGE_CURRECT_SONG_INDEX = 'player/CHANGE_CURRECT_SONG_INDEX'
export const CHANGE_SEQUENCE = 'player/CHANGE_SEQUENCE'
export const CHANGE_LYRICS_LIST = 'player/CHANGE_LYRICS_LIST'
export const CHANGE_SIMI_PLAYLIST = "player/CHANGE_SIMI_PLAYLIST"
export const CHANGE_SIMI_SONGS = "player/CHANGE_SIMI_SONGS"